# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
 - head-branch: ['feature', 'enhancement']

fix:
  - head-branch: ['fix']

hotfix:
  - head-branch: ['hotfix']

   
